CentOS no longer has "python" package
This fixes the following error when building the Docker image:

```
No match for argument: python
There are following alternatives for "python": python2, python36, python38
No match for argument: python-pip
Error: Unable to find a match: python python-pip
The command '/bin/sh -c yum -y install unzip zip curl git java-1.8.0-openjdk python python-pip && yum clean all' returned a non-zero code: 1
```

CentOS no longer seem to have a default Python version. They require you to choose Python 2 or Python 3.